"""added authentication

Revision ID: 00ea8f6ba1d3
Revises: bd279fc04fbb
Create Date: 2026-06-08 13:40:11.891118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ea8f6ba1d3'
down_revision: Union[str, Sequence[str], None] = 'bd279fc04fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Backfill legacy documents that predate chat scoping.
    # 1) Ensure each affected user has at least one chat.
    op.execute(
        sa.text(
            """
            INSERT INTO chats (user_id, name, created_at, updated_at)
            SELECT DISTINCT d.user_id, 'Migrated Chat', NOW(), NOW()
            FROM documents d
            LEFT JOIN chats c ON c.user_id = d.user_id
            WHERE d.chat_id IS NULL AND c.id IS NULL
            """
        )
    )

    # 2) Attach null-chat documents to an existing chat for that user.
    op.execute(
        sa.text(
            """
            UPDATE documents d
            SET chat_id = c.chat_id
            FROM (
                SELECT user_id, MIN(id) AS chat_id
                FROM chats
                GROUP BY user_id
            ) c
            WHERE d.chat_id IS NULL
              AND d.user_id = c.user_id
            """
        )
    )

    op.alter_column('documents', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'password_hash')
    op.alter_column('documents', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
