"""add_storage_path

Revision ID: 7cabf381fd38
Revises: a67dd3831c51
Create Date: 2026-06-28 19:06:29.213296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cabf381fd38'
down_revision: Union[str, Sequence[str], None] = 'a67dd3831c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_tasks', sa.Column('storage_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_tasks', 'storage_path')
    # ### end Alembic commands ###
